name: Ida server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bisi

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ndubuisi .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ndubuisi

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ndubuisi
            docker stop ida || true
            docker rm ida || true
            docker run -d --name ida -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/ndubuisi
